# 1

In [1]:
arr = [2, 3, 8, 7, 13, 15, 1, 0, 12]

for i in range(len(arr)):
    if i%2 == 0:
        print(arr[i])

2
8
13
1
12


# 2

In [2]:
for i in range(len(arr)):
    if arr[i]%2 == 0:
        print(arr[i])

2
8
0
12


# 3

In [3]:
arr = [-1, 2, 3, -1, -2]

for i in range(len(arr) - 1):
    if (arr[i] >= 0 and arr[i+1] >= 0) or (arr[i] < 0 and arr[i+1] < 0):
        print(arr[i], arr[i+1])
        break

2 3


# 4

In [4]:
heights = [165, 163, 160, 160, 157, 157, 155, 154]
Height = int(input())   

160


In [5]:
for i in range(len(heights)):
    if (Height > heights[i]):
        print(i + 1)
        break 

5


# 5

In [148]:
arr = [1, 2, 2, 3, 3, 3]
print(len(set(arr)))

3


In [150]:
new_arr = []

for element in arr: 
    if element not in new_arr: 
        new_arr.append(element) 

print(len(new_arr))

3


# 6

In [208]:
arr = [3, 4, 5, 2, 1]

for i in range(len(arr)):
    if i == 0:
        min_val = arr[i]
        min_index = i
        max_val = arr[i]
        max_index = i
    else:
        if arr[i] < min_val:
            min_val = arr[i]
            min_index = i
        if arr[i] > max_val:
            max_val = arr[i]
            max_index = i

arr[min_index] = max_val
arr[max_index] = min_val


print(arr)


[3, 4, 1, 2, 5]


# 7

In [61]:
arr = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6]
new_arr = []

for i in range(len(arr)):
    count = 0
    for element in arr:
        if arr[i] == element:
            count += 1
    if count == 1:
         new_arr.append(arr[i])


print(new_arr)


[1, 4, 5]


# 8

In [42]:
N, K = map(int, input().split())

output = []

for i in range(N):
    output.append("I")

for i in range(K):
    x, y = map(int, input().split())
    start = x - 1
    end = y -1
    n = end - start + 1
    for j in range(n):
        output[start + j] = "."
print(output)

10 3
8 10
2 5
3 6
['I', '.', '.', '.', '.', '.', 'I', '.', '.', '.']


# 9

In [93]:
x = []
y = []

for i in range(8):
    xy = input()
    x.append(int(xy.split()[0]))
    y.append(int(xy.split()[1]))
    

for i in range(8):
    count_x = 0
    for element in x:
        if x[i] == element:
            count_x += 1
    if count_x > 1:
        break
    count_y = 0
    for element in y:
        if y[i] == element:
            count_y += 1
    if count_y > 1:
        break

if count_x == 1 and count_y == 1:
    print("YES")
else:
    print("NO")

1 8
2 7 
6 3
4 5
5 4
6 3
7 2
8 2
NO


# 10

In [10]:
n = int(input())

mtx = []
for i in range(n):
    line = input()
    mtx.append(line.split())

for i in range(n):
    for j in range(n):
        mtx[i][j] = int(mtx[i][j])

3 
0 1 2
1 5 3
2 4 6


In [11]:
mtx

[[0, 1, 2], [1, 5, 3], [2, 4, 6]]

In [12]:
bool = True

for i in range(n):
    for j in range(n):
        if i != j:
            if mtx[i][j] != mtx[j][i]:
                bool = False

if bool == True:
    print("YES")
else:
    print("NO")

NO


# 11

In [39]:
n, m = map(int, input().split())

mtx = []
for i in range(n):
    line = input()
    mtx.append(line.split())

for i in range(n):
    for j in range(m):
        mtx[i][j] = int(mtx[i][j])

3 2
2 2
5 4
4 5


In [40]:
mtx

[[2, 2], [5, 4], [4, 5]]

In [41]:
ans = []

for i in range(n):
    sum = 0
    for j in range(m):
        sum = sum + mtx[i][j]
    ans.append(sum)

for i in range(n):
    if i == 0:
        max_val = ans[i]
        max_index = i
    elif ans[i] > max_val:
        max_val = ans[i]
        max_index = i
        
        
print(max_val)
print(max_index)

9
1


# 12

In [42]:
n, m = map(int, input().split())

mtx = []
for i in range(n):
    line = input()
    mtx.append(line.split())

for i in range(n):
    for j in range(m):
        mtx[i][j] = int(mtx[i][j])

3 3
3 1 2
1 3 4
3 3 3


In [46]:
mtx

[[3, 1, 2], [1, 3, 4], [3, 3, 3]]

In [48]:
for i in range(n):
    for j in range(m):
        if i == 0 and j == 0:
            max_val = mtx[i][j]
            row = i
            col = j
        elif mtx[i][j] > max_val:
            max_val = mtx[i][j]
            row = i
            col = j

print(max_val)
print(row, col)

4
1 2


# 13

In [57]:
n, m = map(int, input().split())

mtx = []
for i in range(n):
    line = input()
    mtx.append(line.split())

for i in range(n):
    for j in range(m):
        mtx[i][j] = int(mtx[i][j])

3 3
1 2 7 
1 3 5
4 1 7


In [58]:
mtx

[[1, 2, 7], [1, 3, 5], [4, 1, 7]]

In [60]:
for i in range(n):
    sum = 0
    for j in range(m):
        sum = sum + mtx[i][j]
        if i == 0 and j == 0:
            row = i
        elif mtx[i][j] > max_val:
            row = i
        elif mtx[i][j] == max_val and sum > max_sum:
            row = i
        max_sum = sum
print(row)


2


# 14

In [3]:
n, m = map(int, input().split())

w = int(input())

mtx = []
for i in range(w):
    line = input()
    mtx.append(line.split())

for i in range(w):
    for j in range(m):
        mtx[i][j] = int(mtx[i][j])


3 2
2
1 1
2 2


In [4]:
mtx

[[1, 1], [2, 2]]

In [5]:
desk = [[0]*m]*n

In [6]:
desk

[[0, 0], [0, 0], [0, 0]]

In [23]:
import random
from random import randint
d2 = [[random.randint(0, 10)]*m]*n

In [24]:
d2

[[9, 9], [9, 9], [9, 9]]

In [52]:
d3 = []
import numpy as np
for i in range(n):
    for j in range(m):
        d3[i][j] = np.random.randint(0, 10)

IndexError: list index out of range

In [59]:
import numpy as np
out_arr = np.random.randint(low = 0, high = 10, size = (3, 2))

In [61]:
print(out_arr)

[[8 3]
 [4 5]
 [6 5]]


In [51]:
# importing numpy 
import numpy as geek 
  
# output array 
out_arr = geek.random.randint(2, 10, (2, 3, 4)) 
print ("Output 3D Array filled with random integers : ", out_arr)  

Output 3D Array filled with random integers :  [[[2 3 2 2]
  [4 7 7 3]
  [2 6 4 4]]

 [[3 8 7 7]
  [9 2 8 2]
  [8 7 3 3]]]
